#link "libc";

extern puts :: fn(s: cstring) i32;

main :: fn() void {
    greetings := [_]cstring{c"hello", c"hi", c"hey"};

/* 
    the greetings variable can also be declared in these ways:
    greetings := [3]cstring{c"hello", c"hi", c"hey"};
    greetings: [3]cstring = {c"hello", c"hi", c"hey"};
    greetings: [_]cstring = {c"hello", c"hi", c"hey"};
*/

    greetings[0] = c"wassup";
    puts(greetings[0]);
    puts(greetings[1]);
    puts(greetings[2]);
}
